GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/users 
Content-Type: application/json

{
    "username": "Jon",
    "name": "jon",
    "password": "123"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "Jon",
    "password": "123"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvbiIsImlkIjoiNjUzMWQ4NWEyMGNhZGY1ZWUwZTJlZThiIiwiaWF0IjoxNjk5ODc1MzA5LCJleHAiOjE2OTk4Nzg5MDl9.n24eAMs8OO_qoiDKgSymJ98D94F_ovy4mhxcZCk4HBs

{
     "title": "test moving user to middleware",
    "url": "empty",
    "author": "Jon"
}

###

GET http://localhost:3003/api/comments

###

POST http://localhost:3003/api/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvbiIsImlkIjoiNjUzMWQ4NWEyMGNhZGY1ZWUwZTJlZThiIiwiaWF0IjoxNjk5ODc1MzA5LCJleHAiOjE2OTk4Nzg5MDl9.n24eAMs8OO_qoiDKgSymJ98D94F_ovy4mhxcZCk4HBs

{
     "content": "This is a comment",
     "blogId": "65520a6307bc86c26a1afa59"
}

###

POST http://localhost:3003/api/users 
Content-Type: application/json

{
    "username": "JonnnTL",
    "name": "jon",
    "password": "13"
}


###

DELETE http://localhost:3003/api/blogs/6531f82a369f1d74239abfa1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvbiIsImlkIjoiNjUzMWQ4NWEyMGNhZGY1ZWUwZTJlZThiIiwiaWF0IjoxNjk4MDMxNzMyLCJleHAiOjE2OTgwMzUzMzJ9.jDSdquM1YssCNWW_DlYAjViQ-8TtJ3LqMcExAoXJM08